apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: java-app
  name: javawebapp-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      labels:
        app: javawebapp
    spec:
      containers:
      - name: javawebapp-env
        image: nithin246/javawebapp:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8090


