apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebapp-env-build-number
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javawebapp
      version: "BUILD_NUMBER"
  template:
    metadata:
      labels:
        app: javawebapp
        version: "BUILD_NUMBER"
    spec:
      containers:
      - name: javawebapp-env-build-number
        image: nithin246/javawebapp:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8090

