apiVersion: v1
kind: Service
metadata:
  namespace: java-app
  name: javawebapp-env
  labels:
    app: javawebapp
spec:
  selector:
    app: javawebapp
  ports:
  - protocol: TCP
    port: 8090
    targetPort: 8090

