apiVersion: v1
kind: Service
metadata:
  name: javawebapp-env-build-number
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8090
      name: http
    - name: "https"
      port: 443
      targetPort: 8090
      protocol: "TCP"
  selector:
    app: javawebapp
    version: "build-number"
